### ISSUE TITLE
New version Firefox 71.0: tabs on top again!

### ISSUE THREAD

**Issue by SpeedyKepke** [trogau/firefoxSettings#1]
Hoi,
since the new version of Firefox, again the tabs are on top iso on bottom, despite having adjusted the user.Chrome.css according to the link found on your site: [https://github.com/trogau/firefoxSettings/blob/master/userChrome.css](url).
What can I do to correct this problem, because I don't like the tabs on the top of Firefox!
Thanks in advance for your co-operation.
Speedy

**Comment by trogau** [comment]
I have updated the file with new code from https://github.com/Aris-t2/CustomCSSforFx which seems to have fixed it for me.  

I recommend switching to the code in the above repository; the maintainer there knows what they are doing and keep the code updated across versions!

**Comment by SpeedyKepke** [comment]
thanks a lot for your quick reply and your co-operation
I've used the css in annex
and everything is OK now

I'm very happy again 😀

[image: 6.JPG]



Op wo 4 dec. 2019 om 02:26 schreef David Harrison <notifications@github.com
