### ISSUE TITLE
Fix for v72 does not work

### ISSUE THREAD

**Issue by unitb-ore** [trogau/firefoxSettings#2]
Hi,

thanks for the userChrome.css, but the fix for v72 does not work for me:

![grafik](https://user-images.githubusercontent.com/8627609/71977464-2421fd80-3219-11ea-8a99-460a029fc45a.png)

**Comment by trogau** [comment]
Thanks, I've made some changes & fixed it now.

**Comment by unitb-ore** [comment]
Thanks a lot! The new version didn't work at my first try ...
... I had to remove this line:

@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"); /* set default namespace to XUL */

... then it worked! :-)
